# #local
export DATABASE_NAME := smartkid-db
export SERVICE_NAME := question
export DATABASE_HOST := localhost
export DATABASE_PORT := 5432
export DATABASE_USER := smartkid-user
export DATABASE_PASSWORD := Smartkid-db-dev-env@2023
# #dev
# export DATABASE_NAME := smartkid-db
# export SERVICE_NAME := question
# export DATABASE_HOST := 54.151.182.196
# export DATABASE_PORT := 5432
# export DATABASE_USER := smartkid-user
# export DATABASE_PASSWORD := Smartkid-db-dev-env@2023
#prod
# export DATABASE_NAME := kidacadbprod
# export SERVICE_NAME := question
# export DATABASE_HOST := 13.251.151.118
# export DATABASE_PORT := 5432
# export DATABASE_USER := kidacauserprod
# export DATABASE_PASSWORD := Kidaca-db-prod-env

include ../base.Makefile