local:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=db-name user=db-user password=db-password sslmode=disable
  dir: migration
  table: schema_migrations ## table contains migration info

development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=db-name user=db-user password=db-password sslmode=disable
  dir: migration
  table: schema_migrations ## table contains migration info