local:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=sampledb user=sampleuser password=samplepassword sslmode=disable
  dir: migration
  table: schema_migrations ## table contains migration info

development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=sampledb user=sampleuser password=samplepassword sslmode=disable
  dir: migration
  table: schema_migrations ## table contains migration info