version: '3.8'

services:
  sample-db:
    image: postgres:14.1-alpine
    container_name: sample-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplepassword
    volumes: 
      - sample-db:/var/lib/postgresql/data
    
volumes:
  sample-db:
    driver: local